In [ ]:
import time

notebook_start_time = time.time()

# Set up environment

In [ ]:
import sys
from pathlib import Path


def is_google_colab() -> bool:
    if "google.colab" in str(get_ipython()):
        return True
    return False


def clone_repository() -> None:
    !git clone https://github.com/decodingml/hands-on-recommender-system.git
    %cd hands-on-recommender-system/


def install_dependencies() -> None:
    !pip install --upgrade uv
    !uv pip install --all-extras --system --requirement pyproject.toml


if is_google_colab():
    clone_repository()
    install_dependencies()

    root_dir = str(Path().absolute())
    print("⛳️ Google Colab environment")
else:
    root_dir = str(Path().absolute().parent)
    print("⛳️ Local environment")

# Add the root directory to the `PYTHONPATH` to use the `recsys` Python module from the notebook.
if root_dir not in sys.path:
    print(f"Adding the following directory to the PYTHONPATH: {root_dir}")
    sys.path.append(root_dir)

⛳️ Local environment

# Training pipeline: Training ranking model </span>

In this notebook, you will train a ranking model using gradient boosted trees.

## Imports

In [ ]:
%load_ext autoreload
%autoreload 2

import warnings

warnings.filterwarnings("ignore")

from loguru import logger

from recsys import hopsworks_integration, training
from recsys.config import settings

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## Constants

In [ ]:
from pprint import pprint

pprint(dict(settings))

{'CUSTOMER_DATA_SIZE': <CustomerDatasetSize.SMALL: 'SMALL'>,
 'CUSTOM_HOPSWORKS_INFERENCE_ENV': 'custom_env_name',
 'FEATURES_EMBEDDING_MODEL_ID': 'all-MiniLM-L6-v2',
 'HOPSWORKS_API_KEY': SecretStr('**********'),
 'OPENAI_API_KEY': SecretStr(''),
 'OPENAI_MODEL_ID': 'gpt-4o-mini',
 'RANKING_DATASET_VALIDATON_SPLIT_SIZE': 0.1,
 'RANKING_EARLY_STOPPING_ROUNDS': 5,
 'RANKING_ITERATIONS': 100,
 'RANKING_LEARNING_RATE': 0.2,
 'RANKING_MODEL_TYPE': 'ranking',
 'RANKING_SCALE_POS_WEIGHT': 10,
 'RECSYS_DIR': WindowsPath('c:/Users/PC/OneDrive - National Economics University/Tài liệu/personalized-recommender-course/recsys'),
 'TWO_TOWER_DATASET_TEST_SPLIT_SIZE': 0.1,
 'TWO_TOWER_DATASET_VALIDATON_SPLIT_SIZE': 0.1,
 'TWO_TOWER_LEARNING_RATE': 0.01,
 'TWO_TOWER_MODEL_BATCH_SIZE': 2048,
 'TWO_TOWER_MODEL_EMBEDDING_SIZE': 16,
 'TWO_TOWER_NUM_EPOCHS': 10,
 'TWO_TOWER_WEIGHT_DECAY': 0.001}

## Connect to Hopsworks Feature Store

In [ ]:
import hopsworks

hopsworks_host = "eu-west.cloud.hopsworks.ai"

project = hopsworks.login(
    host=hopsworks_host,
    api_key_value=settings.HOPSWORKS_API_KEY.get_secret_value()
)

# Thêm logic này để tự tạo project nếu tài khoản bị trống
if project is None:
    project = hopsworks.create_project("recommender_system", description="H&M Recommender")

fs = project.get_feature_store()

2026-03-10 14:36:28,946 INFO: Closing external client and cleaning up certificates.
2026-03-10 14:36:29,098 INFO: Connection closed.
2026-03-10 14:36:29,106 INFO: Initializing external client
2026-03-10 14:36:29,106 INFO: Base URL: https://eu-west.cloud.hopsworks.ai:443
2026-03-10 14:36:32,605 INFO: Python Engine initialized.

Logged in to project, explore it here https://eu-west.cloud.hopsworks.ai:443/p/31873

# Getting the training data

In [ ]:
feature_view_ranking = hopsworks_integration.feature_store.create_ranking_feature_views(
    fs
)

In [ ]:
X_train, X_val, y_train, y_val = feature_view_ranking.train_test_split(
    test_size=settings.RANKING_DATASET_VALIDATON_SPLIT_SIZE,
    description="Ranking training dataset",
)
X_train.head(3)

Finished: Reading data from Hopsworks, using Hopsworks Feature Query Service (6.03s)
2026-03-10 14:37:06,256 INFO: Computing insert statistics
2026-03-10 14:37:06,624 INFO: Computing insert statistics

,age,product_type_name,product_group_name,graphical_appearance_name,colour_group_name,perceived_colour_value_name,perceived_colour_master_name,department_name,index_name,index_group_name,section_name,garment_group_name,month_sin,month_cos
0,48.0,Polo shirt,Garment Upper body,Solid,White,Light,White,Jersey Fancy,Menswear,Menswear,Contemporary Smart,Jersey Fancy,0.5,-8.660254e-01
1,50.0,Dress,Garment Full body,Solid,Dark Beige,Dark,Beige,Knitwear,Ladieswear,Ladieswear,Womens Everyday Collection,Knitwear,-0.5,8.660254e-01
2,26.0,Top,Garment Upper body,Solid,White,Light,White,Jersey,Ladieswear,Ladieswear,Womens Tailoring,Jersey Fancy,-1.0,-1.836970e-16

In [ ]:
y_train.head(3)

   label
0      1
1      1
2      1

# Training the ranking model

Let's train the ranking model:

In [ ]:
model = training.ranking.RankingModelFactory.build()
trainer = training.ranking.RankingModelTrainer(
    model=model, train_dataset=(X_train, y_train), eval_dataset=(X_val, y_val)
)

In [ ]:
trainer.fit()

0:	learn: 0.5148683	test: 0.5149081	best: 0.5149081 (0)	total: 165ms	remaining: 16.3s
1:	learn: 0.3950439	test: 0.3951204	best: 0.3951204 (1)	total: 246ms	remaining: 12s
2:	learn: 0.3092757	test: 0.3093850	best: 0.3093850 (2)	total: 346ms	remaining: 11.2s
3:	learn: 0.2454958	test: 0.2456312	best: 0.2456312 (3)	total: 439ms	remaining: 10.5s
4:	learn: 0.1969518	test: 0.1971111	best: 0.1971111 (4)	total: 501ms	remaining: 9.51s
5:	learn: 0.1593917	test: 0.1595784	best: 0.1595784 (5)	total: 547ms	remaining: 8.57s
6:	learn: 0.1300034	test: 0.1302172	best: 0.1302172 (6)	total: 618ms	remaining: 8.21s
7:	learn: 0.1068122	test: 0.1070480	best: 0.1070480 (7)	total: 699ms	remaining: 8.04s
8:	learn: 0.0884084	test: 0.0886619	best: 0.0886619 (8)	total: 802ms	remaining: 8.11s
9:	learn: 0.0737218	test: 0.0739996	best: 0.0739996 (9)	total: 847ms	remaining: 7.62s
10:	learn: 0.0619787	test: 0.0622789	best: 0.0622789 (10)	total: 904ms	remaining: 7.32s
11:	learn: 0.0525785	test: 0.0529006	best: 0.0529006 (11)	total: 1.01s	remaining: 7.4s
12:	learn: 0.0450406	test: 0.0453846	best: 0.0453846 (12)	total: 1.1s	remaining: 7.38s
13:	learn: 0.0389873	test: 0.0393524	best: 0.0393524 (13)	total: 1.18s	remaining: 7.22s
14:	learn: 0.0341317	test: 0.0345169	best: 0.0345169 (14)	total: 1.22s	remaining: 6.94s
15:	learn: 0.0302444	test: 0.0306488	best: 0.0306488 (15)	total: 1.28s	remaining: 6.74s
16:	learn: 0.0271341	test: 0.0275563	best: 0.0275563 (16)	total: 1.34s	remaining: 6.55s
17:	learn: 0.0246678	test: 0.0251059	best: 0.0251059 (17)	total: 1.44s	remaining: 6.58s
18:	learn: 0.0226861	test: 0.0231407	best: 0.0231407 (18)	total: 1.49s	remaining: 6.36s
19:	learn: 0.0211115	test: 0.0215814	best: 0.0215814 (19)	total: 1.54s	remaining: 6.17s
20:	learn: 0.0198641	test: 0.0203482	best: 0.0203482 (20)	total: 1.6s	remaining: 6.02s
21:	learn: 0.0188981	test: 0.0194082	best: 0.0194082 (21)	total: 1.77s	remaining: 6.27s
22:	learn: 0.0181341	test: 0.0186568	best: 0.0186568 (22)	total: 1.94s	remaining: 6.5s
23:	learn: 0.0175101	test: 0.0180442	best: 0.0180442 (23)	total: 2.01s	remaining: 6.37s
24:	learn: 0.0170164	test: 0.0175591	best: 0.0175591 (24)	total: 2.26s	remaining: 6.79s
25:	learn: 0.0166291	test: 0.0171802	best: 0.0171802 (25)	total: 2.36s	remaining: 6.72s
26:	learn: 0.0163208	test: 0.0168791	best: 0.0168791 (26)	total: 2.42s	remaining: 6.53s
27:	learn: 0.0160774	test: 0.0166496	best: 0.0166496 (27)	total: 2.65s	remaining: 6.81s
28:	learn: 0.0158843	test: 0.0164612	best: 0.0164612 (28)	total: 2.77s	remaining: 6.78s
29:	learn: 0.0157313	test: 0.0163338	best: 0.0163338 (29)	total: 2.96s	remaining: 6.9s
30:	learn: 0.0156121	test: 0.0162199	best: 0.0162199 (30)	total: 3.1s	remaining: 6.91s
31:	learn: 0.0155127	test: 0.0161237	best: 0.0161237 (31)	total: 3.29s	remaining: 6.98s
32:	learn: 0.0154274	test: 0.0160399	best: 0.0160399 (32)	total: 3.44s	remaining: 7s
33:	learn: 0.0153598	test: 0.0159796	best: 0.0159796 (33)	total: 3.52s	remaining: 6.84s
34:	learn: 0.0153422	test: 0.0159522	best: 0.0159522 (34)	total: 3.72s	remaining: 6.92s
35:	learn: 0.0153419	test: 0.0159515	best: 0.0159515 (35)	total: 3.79s	remaining: 6.74s
36:	learn: 0.0153417	test: 0.0159509	best: 0.0159509 (36)	total: 3.87s	remaining: 6.59s
37:	learn: 0.0152886	test: 0.0158996	best: 0.0158996 (37)	total: 3.95s	remaining: 6.44s
38:	learn: 0.0152885	test: 0.0158992	best: 0.0158992 (38)	total: 3.98s	remaining: 6.23s
39:	learn: 0.0152476	test: 0.0158601	best: 0.0158601 (39)	total: 4.07s	remaining: 6.11s
40:	learn: 0.0152334	test: 0.0158336	best: 0.0158336 (40)	total: 4.14s	remaining: 5.96s
41:	learn: 0.0152331	test: 0.0158335	best: 0.0158335 (41)	total: 4.2s	remaining: 5.8s
42:	learn: 0.0152301	test: 0.0158287	best: 0.0158287 (42)	total: 4.37s	remaining: 5.8s
43:	learn: 0.0151976	test: 0.0157977	best: 0.0157977 (43)	total: 4.43s	remaining: 5.64s
44:	learn: 0.0151970	test: 0.0157973	best: 0.0157973 (44)	total: 4.57s	remaining: 5.59s
45:	learn: 0.0151968	test: 0.0157971	best: 0.0157971 (45)	total: 4.69s	remaining: 5.51s
46:	learn: 0.0151968	test: 0.0157970	best: 0.0157970 (46)	total: 4.75s	remaining: 5.36s
47:	learn: 0.0151967	test: 0.0157969	best: 0.0157969 (47)	total: 4.85s	remaining: 5.26s
48:	learn: 0.0151677	test: 0.0157745	best: 0.0157745 (48)	total: 5.02s	remaining: 5.22s
49:	learn: 0.0151464	test: 0.0157561	best: 0.0157561 (49)	total: 5.1s	remaining: 5.1s
50:	learn: 0.0151463	test: 0.0157560	best: 0.0157560 (50)	total: 5.17s	remaining: 4.97s
51:	learn: 0.0151442	test: 0.0157477	best: 0.0157477 (51)	total: 5.3s	remaining: 4.89s
52:	learn: 0.0151433	test: 0.0157442	best: 0.0157442 (52)	total: 5.45s	remaining: 4.83s
53:	learn: 0.0151389	test: 0.0157434	best: 0.0157434 (53)	total: 5.62s	remaining: 4.79s
54:	learn: 0.0151235	test: 0.0157296	best: 0.0157296 (54)	total: 5.72s	remaining: 4.68s
55:	learn: 0.0151234	test: 0.0157292	best: 0.0157292 (55)	total: 5.78s	remaining: 4.54s
56:	learn: 0.0151232	test: 0.0157277	best: 0.0157277 (56)	total: 5.95s	remaining: 4.49s
57:	learn: 0.0151231	test: 0.0157274	best: 0.0157274 (57)	total: 6.01s	remaining: 4.35s
58:	learn: 0.0151228	test: 0.0157284	best: 0.0157274 (57)	total: 6.09s	remaining: 4.23s
59:	learn: 0.0151227	test: 0.0157283	best: 0.0157274 (57)	total: 6.14s	remaining: 4.1s
60:	learn: 0.0151226	test: 0.0157282	best: 0.0157274 (57)	total: 6.21s	remaining: 3.97s
61:	learn: 0.0151215	test: 0.0157276	best: 0.0157274 (57)	total: 6.29s	remaining: 3.86s
62:	learn: 0.0151212	test: 0.0157262	best: 0.0157262 (62)	total: 6.4s	remaining: 3.76s
63:	learn: 0.0151212	test: 0.0157262	best: 0.0157262 (62)	total: 6.46s	remaining: 3.63s
64:	learn: 0.0151212	test: 0.0157263	best: 0.0157262 (62)	total: 6.53s	remaining: 3.51s
65:	learn: 0.0151210	test: 0.0157260	best: 0.0157260 (65)	total: 6.64s	remaining: 3.42s
66:	learn: 0.0151210	test: 0.0157259	best: 0.0157259 (66)	total: 6.71s	remaining: 3.3s
67:	learn: 0.0151208	test: 0.0157251	best: 0.0157251 (67)	total: 6.82s	remaining: 3.21s
68:	learn: 0.0151208	test: 0.0157251	best: 0.0157251 (68)	total: 6.89s	remaining: 3.1s
69:	learn: 0.0151208	test: 0.0157245	best: 0.0157245 (69)	total: 6.96s	remaining: 2.98s
70:	learn: 0.0151207	test: 0.0157240	best: 0.0157240 (70)	total: 7.02s	remaining: 2.87s
71:	learn: 0.0151205	test: 0.0157235	best: 0.0157235 (71)	total: 7.13s	remaining: 2.77s
72:	learn: 0.0151205	test: 0.0157231	best: 0.0157231 (72)	total: 7.2s	remaining: 2.66s
73:	learn: 0.0151204	test: 0.0157230	best: 0.0157230 (73)	total: 7.26s	remaining: 2.55s
74:	learn: 0.0151204	test: 0.0157226	best: 0.0157226 (74)	total: 7.32s	remaining: 2.44s
75:	learn: 0.0151204	test: 0.0157225	best: 0.0157225 (75)	total: 7.38s	remaining: 2.33s
76:	learn: 0.0151203	test: 0.0157226	best: 0.0157225 (75)	total: 7.44s	remaining: 2.22s
77:	learn: 0.0151203	test: 0.0157224	best: 0.0157224 (77)	total: 7.5s	remaining: 2.12s
78:	learn: 0.0151199	test: 0.0157216	best: 0.0157216 (78)	total: 7.58s	remaining: 2.02s
79:	learn: 0.0151199	test: 0.0157217	best: 0.0157216 (78)	total: 7.77s	remaining: 1.94s
80:	learn: 0.0151198	test: 0.0157214	best: 0.0157214 (80)	total: 7.84s	remaining: 1.84s
81:	learn: 0.0151198	test: 0.0157212	best: 0.0157212 (81)	total: 7.92s	remaining: 1.74s
82:	learn: 0.0151198	test: 0.0157211	best: 0.0157211 (82)	total: 8.03s	remaining: 1.64s
83:	learn: 0.0151198	test: 0.0157209	best: 0.0157209 (83)	total: 8.11s	remaining: 1.54s
84:	learn: 0.0151198	test: 0.0157208	best: 0.0157208 (84)	total: 8.17s	remaining: 1.44s
85:	learn: 0.0151198	test: 0.0157208	best: 0.0157208 (85)	total: 8.25s	remaining: 1.34s
86:	learn: 0.0151197	test: 0.0157208	best: 0.0157208 (85)	total: 8.31s	remaining: 1.24s
87:	learn: 0.0151197	test: 0.0157208	best: 0.0157208 (85)	total: 8.38s	remaining: 1.14s
88:	learn: 0.0151197	test: 0.0157207	best: 0.0157207 (88)	total: 8.45s	remaining: 1.04s
89:	learn: 0.0151197	test: 0.0157208	best: 0.0157207 (88)	total: 8.51s	remaining: 946ms
90:	learn: 0.0151197	test: 0.0157207	best: 0.0157207 (88)	total: 8.57s	remaining: 847ms
91:	learn: 0.0151197	test: 0.0157206	best: 0.0157206 (91)	total: 8.66s	remaining: 753ms
92:	learn: 0.0151197	test: 0.0157206	best: 0.0157206 (92)	total: 8.72s	remaining: 656ms
93:	learn: 0.0151193	test: 0.0157206	best: 0.0157206 (92)	total: 8.83s	remaining: 564ms
94:	learn: 0.0151190	test: 0.0157207	best: 0.0157206 (92)	total: 8.94s	remaining: 470ms
95:	learn: 0.0151190	test: 0.0157207	best: 0.0157206 (92)	total: 9.01s	remaining: 375ms
96:	learn: 0.0151190	test: 0.0157206	best: 0.0157206 (92)	total: 9.16s	remaining: 283ms
97:	learn: 0.0151189	test: 0.0157205	best: 0.0157205 (97)	total: 9.28s	remaining: 189ms
98:	learn: 0.0151189	test: 0.0157204	best: 0.0157204 (98)	total: 9.34s	remaining: 94.3ms
99:	learn: 0.0151188	test: 0.0157203	best: 0.0157203 (99)	total: 9.45s	remaining: 0us

bestTest = 0.01572031905
bestIteration = 99

## Evaluating the ranking model

Next, you'll evaluate how well the model performs on the validation data using metrics for classification such as precision, recall and f1-score:

In [ ]:
metrics = trainer.evaluate(log=True)

2026-03-10 14:37:22.549 | INFO     | recsys.training.ranking:evaluate:62 -               precision    recall  f1-score   support

           0       1.00      1.00      1.00     19883
           1       0.95      1.00      0.98      1946

    accuracy                           1.00     21829
   macro avg       0.98      1.00      0.99     21829
weighted avg       1.00      1.00      1.00     21829

It can be seen that the model has a low F1-score on the positive class (higher is better). The performance could potentially be improved by adding more features to the dataset, e.g. image embeddings.

Let's see which features your model considers important.

In [ ]:
trainer.get_feature_importance()

{'month_cos': 62.71082892878465,
 'month_sin': 35.47164233952842,
 'age': 0.42030031033362303,
 'product_group_name': 0.26463735632256546,
 'index_name': 0.20643825682732267,
 'section_name': 0.1914622939853796,
 'department_name': 0.19129755418303543,
 'perceived_colour_master_name': 0.16251189772141175,
 'graphical_appearance_name': 0.12016199083586425,
 'garment_group_name': 0.08767264772542131,
 'perceived_colour_value_name': 0.08664028306164895,
 'index_group_name': 0.04084936086397908,
 'colour_group_name': 0.028482852255127766,
 'product_type_name': 0.017073927571579075}

## Uploading the model to Hopsworks model registry

In [ ]:
mr = project.get_model_registry()

In [ ]:
ranking_module = hopsworks_integration.ranking_serving.HopsworksRankingModel(
    model=model
)
ranking_module.register(mr, feature_view_ranking, X_train, metrics)

Uploading c:\Users\PC\OneDrive - National Economics University\Tài liệu\personalized-recommender-course\notebooks\ranking_model.pkl: 100.000%|██████████| 413412/413412 elapsed<00:02 remaining<00:00
Uploading c:\Users\PC\OneDrive - National Economics University\Tài liệu\personalized-recommender-course\notebooks\input_example.json: 100.000%|██████████| 433/433 elapsed<00:01 remaining<00:00
Uploading c:\Users\PC\OneDrive - National Economics University\Tài liệu\personalized-recommender-course\notebooks\model_schema.json: 100.000%|██████████| 1338/1338 elapsed<00:01 remaining<00:00
Model export complete: 100%|██████████| 6/6 [00:16<00:00,  2.72s/it]

Model created, explore it at https://eu-west.cloud.hopsworks.ai:443/p/31873/models/ranking_model/2

## Inspecting the model in the Hopsworks model registry </span>

View results in [Hopsworks Serverless](https://rebrand.ly/serverless-github): **Data Science → Model Registry**

---

In [ ]:
notebook_end_time = time.time()
notebook_execution_time = notebook_end_time - notebook_start_time

logger.info(
    f"⌛️ Notebook Execution time: {notebook_execution_time:.2f} seconds ~ {notebook_execution_time / 60:.2f} minutes"
)

2026-03-10 14:37:45.024 | INFO     | __main__:<module>:4 - ⌛️ Notebook Execution time: 80.23 seconds ~ 1.34 minutes